### ISSUE TITLE
企业微信应用

### ISSUE THREAD

**Issue by Fofade** [HCLonely/all-pusher-api#3]
如下，企业微信应用代码56行赋值写错了。
![image](https://user-images.githubusercontent.com/34083175/225189216-eb76c0c2-3ce5-4122-87c7-29e003d98d27.png)
修改后可正常使用
![image](https://user-images.githubusercontent.com/34083175/225189334-35408a28-6eda-4c1c-a990-eac6bc204502.png)

**Comment by HCLonely** [comment]
感谢反馈，已修复
